using System.IO;
using System.CodeDom.Compiler;

namespace protoc_gen_turbolink.Template
{
    public class ClientH
    {
        private readonly GrpcServiceFile s;
        private readonly GenerateParam g;

        public ClientH(GrpcServiceFile _s, GenerateParam _g)
        {
            s = _s;
            g = _g;
        }

        public string TransformText()
        {
            using (var sw = new StringWriter())
            using (var writer = new IndentedTextWriter(sw, "\t"))
            {
                // 1. 文件头和包含
                writer.WriteLine("//Generated by TurboLink CodeGenerator, do not edit!");
                writer.WriteLine("#pragma once");
                writer.WriteLine("#include \"TurboLinkGrpcClient.h\"");
                writer.WriteLine($"#include \"{s.TurboLinkBasicFileName}Message.h\"");

                if (s.ServiceArray.Count > 0)
                {
                    writer.WriteLine($"#include \"{s.CamelFileName}Client.generated.h\"");
                }
                writer.WriteLine();

                // 2. 遍历 Service 生成 Delegate 和 Class
                foreach (var service in s.ServiceArray)
                {
                    // 2.1 生成委托 (Delegates)
                    foreach (var method in service.MethodArray)
                    {
                        if (method.ClientStreaming)
                        {
                            writer.WriteLine($"DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOn{service.Name}{method.Name}WriteComplete, FGrpcContextHandle, Handle);");
                        }
                        writer.WriteLine($"DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOn{service.Name}{method.Name}Response, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const {method.OutputType}&, Response);");
                    }
                    writer.WriteLine();

                    // 2.2 生成 UClass
                    writer.WriteLine("UCLASS(ClassGroup = TurboLink, BlueprintType)");
                    writer.WriteLine($"class {g.ExportPrefix} U{service.Name}Client : public UGrpcClient");
                    writer.WriteLine("{");
                    writer.Indent++;
                    writer.WriteLine("GENERATED_BODY()");
                    writer.WriteLine();

                    // 2.3 生成属性 (Properties / Delegates Instances)
                    writer.Indent--;
                    writer.WriteLine("public:");
                    writer.Indent++;
                    foreach (var method in service.MethodArray)
                    {
                        if (method.ClientStreaming)
                        {
                            writer.WriteLine("UPROPERTY(BlueprintAssignable)");
                            writer.WriteLine($"FOn{service.Name}{method.Name}WriteComplete On{method.Name}WriteComplete;");
                            writer.WriteLine();
                        }
                        writer.WriteLine("UPROPERTY(BlueprintAssignable)");
                        writer.WriteLine($"FOn{service.Name}{method.Name}Response On{method.Name}Response;");
                        writer.WriteLine();
                    }

                    // 2.4 生成函数声明 (UFUNCTIONS)
                    writer.Indent--;
                    writer.WriteLine("public:");
                    writer.Indent++;
                    foreach (var method in service.MethodArray)
                    {
                        writer.WriteLine("UFUNCTION(BlueprintCallable, Category = TurboLink)");
                        writer.WriteLine($"FGrpcContextHandle Init{method.Name}();");
                        writer.WriteLine();

                        writer.WriteLine("UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))");
                        writer.WriteLine($"void {method.Name}(FGrpcContextHandle Handle, const {method.InputType}& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);");
                        writer.WriteLine();

                        if (method.ClientStreaming && !method.ServerStreaming)
                        {
                            writer.WriteLine("UFUNCTION(BlueprintCallable, Category = TurboLink)");
                            writer.WriteLine($"void Stop{method.Name}(FGrpcContextHandle Handle);");
                            writer.WriteLine();
                        }
                    }

                    // 2.5 生成公共成员函数
                    writer.Indent--;
                    writer.WriteLine("public:");
                    writer.Indent++;
                    writer.WriteLine("virtual void Shutdown() override;");
                    writer.WriteLine();
                    writer.WriteLine("UFUNCTION(BlueprintCallable, Category = TurboLink)");
                    writer.WriteLine("void TryCancel(FGrpcContextHandle Handle);");

                    writer.Indent--;
                    writer.WriteLine("};");
                    writer.WriteLine();
                }

                return sw.ToString();
            }
        }
    }
}
