using System.IO;
using System.CodeDom.Compiler;

namespace protoc_gen_turbolink.Template
{
    public class ClientCPP
    {
        private readonly GrpcServiceFile s;
        private readonly GenerateParam g;

        public ClientCPP(GrpcServiceFile _s, GenerateParam _g)
        {
            s = _s;
            g = _g;
        }

        public string TransformText()
        {
            using (var sw = new StringWriter())
            using (var writer = new IndentedTextWriter(sw, "\t")) // Unreal 习惯用 Tab
            {
                // 1. 写入头文件包含
                writer.WriteLine("//Generated by TurboLink CodeGenerator, do not edit!");
                writer.WriteLine($"#include \"{s.TurboLinkBasicFileName}Client.h\"");
                writer.WriteLine($"#include \"{s.TurboLinkBasicFileName}Service.h\"");
                writer.WriteLine($"#include \"{s.CamelFileName}Context.h\"");
                writer.WriteLine("#include \"TurboLinkGrpcManager_Private.h\"");
                writer.WriteLine("#include \"Templates/SharedPointer.h\"");
                writer.WriteLine();

                // 2. 遍历 Service
                foreach (var service in s.ServiceArray)
                {
                    string className = $"U{service.Name}Client";

                    // 3. 遍历 Method
                    foreach (var method in service.MethodArray)
                    {
                        GenerateInitMethod(writer, className, service, method);
                        GenerateCallMethod(writer, className, service, method);

                        // 如果是 ClientStreaming 且不是 ServerStreaming，生成 Stop 函数
                        if (method.ClientStreaming && !method.ServerStreaming)
                        {
                            GenerateStopMethod(writer, className, service, method);
                        }
                    }

                    // 4. 生成 TryCancel
                    GenerateTryCancel(writer, className);

                    // 5. 生成 Shutdown
                    GenerateShutdown(writer, className, service);
                }

                return sw.ToString();
            }
        }

        private void GenerateInitMethod(IndentedTextWriter writer, string className, GrpcService service, GrpcServiceMethod method)
        {
            writer.WriteLine($"FGrpcContextHandle {className}::Init{method.Name}()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();");
            writer.WriteLine($"auto context = UGrpcClient::MakeContext<GrpcContext_{service.Name}_{method.Name}>(handle);");
            writer.WriteLine("context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();");
            
            if (method.ClientStreaming)
            {
                writer.WriteLine("context->Init();");
            }
            
            writer.WriteLine("return context->GetHandle();");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();
        }

        private void GenerateCallMethod(IndentedTextWriter writer, string className, GrpcService service, GrpcServiceMethod method)
        {
            writer.WriteLine($"void {className}::{method.Name}(FGrpcContextHandle Handle, const {method.InputType}& Request, FGrpcMetaData MetaData, float DeadLineSeconds)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("auto context = UGrpcClient::GetContext(Handle);");
            writer.WriteLine("if (context != nullptr)");
            writer.WriteLine("{");
            writer.Indent++;
            
            string contextTypeName = $"GrpcContext_{service.Name}_{method.Name}";
            writer.WriteLine($"auto context{method.Name} = StaticCastSharedPtr<{contextTypeName}>(*context);");
            
            // 处理 MetaData 循环
            writer.WriteLine("for (const auto& metaDataPair : MetaData.MetaData)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"context{method.Name}->RpcContext->AddMetadata(");
            writer.Indent++;
            writer.WriteLine("TCHAR_TO_UTF8(*(metaDataPair.Key)),");
            writer.WriteLine("TCHAR_TO_UTF8(*(metaDataPair.Value))");
            writer.Indent--;
            writer.WriteLine(");");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();

            // 处理 Deadline
            writer.WriteLine("if (DeadLineSeconds > 0.f)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("std::chrono::time_point deadLine = std::chrono::system_clock::now() + ");
            writer.Indent++;
            writer.WriteLine("std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));");
            writer.Indent--;
            writer.WriteLine($"context{method.Name}->RpcContext->set_deadline(deadLine);");
            writer.Indent--;
            writer.WriteLine("}");

            writer.WriteLine($"context{method.Name}->Call(Request);");
            
            writer.Indent--; // end if context != null
            writer.WriteLine("}");
            writer.Indent--; // end function
            writer.WriteLine("}");
            writer.WriteLine();
        }

        private void GenerateStopMethod(IndentedTextWriter writer, string className, GrpcService service, GrpcServiceMethod method)
        {
            writer.WriteLine($"void {className}::Stop{method.Name}(FGrpcContextHandle Handle)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("auto context = UGrpcClient::GetContext(Handle);");
            writer.WriteLine("if (context != nullptr)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"auto context{method.Name} = StaticCastSharedPtr<GrpcContext_{service.Name}_{method.Name}>(*context);");
            writer.WriteLine($"context{method.Name}->Stop();");
            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();
        }

        private void GenerateTryCancel(IndentedTextWriter writer, string className)
        {
            writer.WriteLine($"void {className}::TryCancel(FGrpcContextHandle Handle)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("auto context = UGrpcClient::GetContext(Handle);");
            writer.WriteLine("if (context != nullptr)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("(*context)->TryCancel();");
            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();
        }

        private void GenerateShutdown(IndentedTextWriter writer, string className, GrpcService service)
        {
            writer.WriteLine($"void {className}::Shutdown()");
            writer.WriteLine("{");
            writer.Indent++;
            
            foreach (var method in service.MethodArray)
            {
                writer.WriteLine($"On{method.Name}Response.Clear();");
            }
            
            writer.WriteLine("Super::Shutdown();");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();
        }
    }
}
