using System.IO;
using System.CodeDom.Compiler;

namespace protoc_gen_turbolink.Template
{
    public class ContextCPP
    {
        private readonly GrpcServiceFile s;
        private readonly GenerateParam g;

        public ContextCPP(GrpcServiceFile _s, GenerateParam _g)
        {
            s = _s;
            g = _g;
        }

        public string TransformText()
        {
            using (var sw = new StringWriter())
            using (var writer = new IndentedTextWriter(sw, "\t"))
            {
                writer.WriteLine("//Generated by TurboLink CodeGenerator, do not edit!");
                writer.WriteLine($"#include \"{s.CamelFileName}Context.h\"");
                writer.WriteLine($"#include \"{s.TurboLinkBasicFileName}Client.h\"");
                writer.WriteLine($"#include \"{s.CamelFileName}Service_Private.h\"");
                writer.WriteLine($"#include \"{s.CamelFileName}Marshaling.h\"");

                foreach (var dependency in s.DependencyFiles)
                {
                    writer.WriteLine($"#include \"{dependency.TurboLinkBasicFileName}Marshaling.h\"");
                }
                writer.WriteLine("#include \"TurboLinkGrpcManager.h\"");

                foreach (var service in s.ServiceArray)
                {
                    foreach (var method in service.MethodArray)
                    {
                        string contextClassName = $"GrpcContext_{service.Name}_{method.Name}";

                        // 1. Constructor
                        writer.WriteLine();
                        writer.WriteLine($"{contextClassName}::{contextClassName}(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)");
                        writer.WriteLine("\t: Super(_Handle, _Service, _Client)");
                        writer.WriteLine("{");
                        writer.WriteLine("}");

                        // 2. Init Method (Only for Client Streaming)
                        if (method.ClientStreaming)
                        {
                            GenerateInitMethod(writer, contextClassName, service, method);
                        }

                        // 3. Call Method (Logic varies by streaming type)
                        GenerateCallMethod(writer, contextClassName, service, method);

                        // 4. Stop Method (Client Streaming but NOT Server Streaming)
                        if (method.ClientStreaming && !method.ServerStreaming)
                        {
                            GenerateStopMethod(writer, contextClassName);
                        }

                        // 5. OnRpcEvent Method
                        GenerateOnRpcEvent(writer, contextClassName, service, method);
                    }
                }
                return sw.ToString();
            }
        }

        private void GenerateInitMethod(IndentedTextWriter writer, string className, GrpcService service, GrpcServiceMethod method)
        {
            writer.WriteLine();
            writer.WriteLine($"void {className}::Init()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("check(GetState() == EGrpcContextState::Ready);");
            writer.WriteLine("UpdateState(EGrpcContextState::Initialing);");
            writer.WriteLine();
            writer.WriteLine($"U{service.Name}* service = (U{service.Name}*)Service;");

            if (method.ServerStreaming) // Bidi-Streaming
            {
                writer.WriteLine($"RpcReaderWriter = service->d->Stub->Async{method.Name}(RpcContext.get(), service->TurboLinkManager->d->CompletionQueue.get(), InitialTag);");
            }
            else // Client-Streaming only
            {
                writer.WriteLine($"RpcReaderWriter = service->d->Stub->Async{method.Name}(RpcContext.get(), &(Super::RpcResponse), service->TurboLinkManager->d->CompletionQueue.get(), InitialTag);");
            }

            writer.Indent--;
            writer.WriteLine("}");
        }

        private void GenerateCallMethod(IndentedTextWriter writer, string className, GrpcService service, GrpcServiceMethod method)
        {
            writer.WriteLine();
            writer.WriteLine($"void {className}::Call(const {method.InputType}& Request)");
            writer.WriteLine("{");
            writer.Indent++;

            if (!method.ClientStreaming) // Unary or Server Streaming
            {
                writer.WriteLine("check(GetState() == EGrpcContextState::Ready);");
                writer.WriteLine("UpdateState(EGrpcContextState::Initialing);");
            }

            writer.WriteLine($"{method.GrpcInputType} rpcRequest;");
            writer.WriteLine("TURBOLINK_TO_GRPC(&Request, &rpcRequest);");
            writer.WriteLine();
            writer.WriteLine($"U{service.Name}* service = (U{service.Name}*)Service;");

            if (method.ClientStreaming)
            {
                writer.WriteLine("if (bCanSend) {");
                writer.Indent++;
                writer.WriteLine("RpcReaderWriter->Write(rpcRequest, WriteTag);");
                writer.WriteLine("bCanSend = false;");
                writer.Indent--;
                writer.WriteLine("}");
                writer.WriteLine("else {");
                writer.Indent++;
                writer.WriteLine("SendQueue.push_back(rpcRequest);");
                writer.Indent--;
                writer.WriteLine("}");
            }
            else if (method.ServerStreaming)
            {
                writer.WriteLine($"RpcReaderWriter = service->d->Stub->Async{method.Name}(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get(), InitialTag);");
            }
            else // Unary
            {
                writer.WriteLine($"RpcReaderWriter = service->d->Stub->Async{method.Name}(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());");
                writer.WriteLine("RpcReaderWriter->ReadInitialMetadata(InitialTag);");
            }

            writer.Indent--;
            writer.WriteLine("}");
        }

        private void GenerateStopMethod(IndentedTextWriter writer, string className)
        {
            writer.WriteLine();
            writer.WriteLine($"void {className}::Stop()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("RpcReaderWriter->WritesDone(WriteTag);");
            writer.WriteLine("bWritesDone = true;");
            writer.Indent--;
            writer.WriteLine("}");
        }

        private void GenerateOnRpcEvent(IndentedTextWriter writer, string className, GrpcService service, GrpcServiceMethod method)
        {
            writer.WriteLine();
            writer.WriteLine($"void {className}::OnRpcEvent(bool Ok, const void* EventTag)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("Super::OnRpcEventInternal(Ok, EventTag, ");
            writer.Indent++;
            writer.WriteLine($"[this](const FGrpcResult& _Result, {method.GrpcOutputType}* _RpcResponse) ");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"U{service.Name}Client* client = (U{service.Name}Client*)(this->Client);");
            writer.WriteLine($"if (!(client->On{method.Name}Response.IsBound())) return;");
            writer.WriteLine();
            writer.WriteLine($"{method.OutputType} response;");
            writer.WriteLine("if (_RpcResponse) {");
            writer.Indent++;
            writer.WriteLine("GRPC_TO_TURBOLINK(_RpcResponse, &response);");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine($"client->On{method.Name}Response.Broadcast(Handle, _Result, response);");
            writer.Indent--;
            writer.Write("}");

            if (method.ClientStreaming)
            {
                writer.WriteLine(",");
                writer.WriteLine("[this]() ");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"U{service.Name}Client* client = (U{service.Name}Client*)(this->Client);");
                writer.WriteLine($"if (!(client->On{method.Name}WriteComplete.IsBound())) return;");
                writer.WriteLine();
                writer.WriteLine($"client->On{method.Name}WriteComplete.Broadcast(Handle);");
                writer.Indent--;
                writer.Write("}");
            }
            writer.WriteLine();
            writer.Indent--; // Align with Super::OnRpcEventInternal
            writer.WriteLine(");");
            writer.Indent--;
            writer.WriteLine("}");
        }
    }
}
