using System.IO;
using System.CodeDom.Compiler;

namespace protoc_gen_turbolink.Template
{
    public class ContextH
    {
        private readonly GrpcServiceFile s;
        private readonly GenerateParam g;

        public ContextH(GrpcServiceFile _s, GenerateParam _g)
        {
            s = _s;
            g = _g;
        }

        public string TransformText()
        {
            using (var sw = new StringWriter())
            using (var writer = new IndentedTextWriter(sw, "\t"))
            {
                // 1. 文件头包含
                writer.WriteLine("//Generated by TurboLink CodeGenerator, do not edit!");
                writer.WriteLine("#pragma once");
                writer.WriteLine("#include \"TurboLinkGrpcContext.h\"");
                writer.WriteLine($"#include \"{s.TurboLinkBasicFileName}Message.h\"");
                writer.WriteLine($"#include \"{s.TurboLinkBasicFileName}Marshaling.h\"");

                // 2. 遍历 Service 和 Method
                foreach (var service in s.ServiceArray)
                {
                    foreach (var method in service.MethodArray)
                    {
                        writer.WriteLine();
                        
                        // 3. 构建 SuperClass 模板字符串
                        string superClass = BuildSuperClass(service, method);
                        string contextClassName = $"GrpcContext_{service.Name}_{method.Name}";

                        // 4. 类定义开始
                        writer.WriteLine($"class {contextClassName} : public {superClass}");
                        writer.WriteLine("{");
                        writer.Indent++;

                        // 5. Friend 和 Typedef
                        writer.WriteLine($"friend class U{service.Name}Client;");
                        writer.WriteLine($"typedef {superClass} Super;");
                        writer.WriteLine();

                        // 6. Private 成员函数
                        writer.WriteLine("private:");
                        writer.Indent++;

                        if (method.ClientStreaming)
                        {
                            writer.WriteLine("void Init();");
                        }

                        writer.WriteLine($"void Call(const {method.InputType}& Request);");

                        if (method.ClientStreaming && !method.ServerStreaming)
                        {
                            writer.WriteLine("void Stop();");
                        }

                        writer.WriteLine("virtual void OnRpcEvent(bool Ok, const void* EventTag) override;");
                        writer.Indent--;
                        writer.WriteLine();

                        // 7. Public 构造函数
                        writer.WriteLine("public:");
                        writer.Indent++;
                        writer.WriteLine($"{contextClassName}(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);");
                        writer.Indent--;

                        // 8. 类结束
                        writer.Indent--;
                        writer.WriteLine("};");
                    }
                }
                return sw.ToString();
            }
        }

        /// <summary>
        /// 构建 C++ 模板基类字符串，例如：TGrpcContext<ReaderWriter, OutputType, [InputType]>
        /// </summary>
        private string BuildSuperClass(GrpcService service, GrpcServiceMethod method)
        {
            // 基础模板名：TGrpcContextUnary / TGrpcContextClientStreaming 等
            string superClass = method.ContextSuperClass;
            
            // 拼接模板参数 1 (ReaderWriter) 和 参数 2 (GrpcOutputType)
            superClass += $"<{service.Name}_{method.Name}_ReaderWriter, {method.GrpcOutputType}";

            // 如果是客户端流，需要增加第三个模板参数 (GrpcInputType)
            if (method.ClientStreaming)
            {
                superClass += $", {method.GrpcInputType}";
            }

            superClass += ">";
            return superClass;
        }
    }
}
