using System;
using System.Collections.Generic;
using System.Text;
using Google.Protobuf.Reflection;

namespace protoc_gen_turbolink.Template
{
    public class MarshalingCPP
    {
        private readonly GrpcServiceFile s;
        private readonly GenerateParam g;

        public MarshalingCPP(GrpcServiceFile _s, GenerateParam _g)
        {
            s = _s;
            g = _g;
        }

        /// <summary>
        /// 生成与原 T4 模板等价的 C++ Marshaling 头文件内容
        /// （相当于原 .tt 的输出结果）
        /// </summary>
        public string TransformText()
        {
            var sb = new StringBuilder();

            // ===== 对应 T4 顶部：固定头部 + 依赖 include =====
            if (!g.SingleOutputFile)
            {
                sb.AppendLine("//Generated by TurboLink CodeGenerator, do not edit!");
                sb.AppendLine($"#include \"{s.CamelFileName}Marshaling.h\"");

                foreach (var dependency in s.DependencyFiles)
                {
                    sb.AppendLine($"#include \"{dependency.TurboLinkBasicFileName}Marshaling.h\"");
                }

                sb.AppendLine();
            }

            // ===== 对应 T4: foreach(GrpcMessage message in s.MessageArray) =====
            var exportedMessages = new HashSet<GrpcMessage>();
            foreach (GrpcMessage message in s.MessageArray)
            {
                var msg = message;
                if (message is GrpcMessage_Oneof)
                {
                    msg = (message as GrpcMessage_Oneof).ParentMessage;   
                }

                if(exportedMessages.Contains(msg)) continue;
                exportedMessages.Add(msg);
                GenerateMessageMarshalingDefine(sb, msg);
                sb.AppendLine();
            }

            return sb.ToString();
        }

        // ==================== 以下是把 <#+ ... #> 改成普通私有方法 ====================

        private string ConvertFieldFromGrpcToTurboLink(GrpcMessageField field, string getField)
        {
            if (field.FieldDesc.Type == FieldDescriptorProto.Types.Type.String)
            {
                return $"StringCast<TCHAR>((const UTF8CHAR*)({getField}.c_str())).Get()";
            }
            else if (field.FieldDesc.Type == FieldDescriptorProto.Types.Type.Bytes)
            {
                return $"FBytes((const uint8*){getField}.c_str(), {getField}.length())";
            }
            else if (field.FieldDesc.Type == FieldDescriptorProto.Types.Type.Enum)
            {
                return $"StaticCast<{field.FieldType}>({getField})";
            }
            
            return getField;
        }

        private string ConvertFieldFromTurboLinkToGrpc(GrpcMessageField field, string getField, string tag = CommentTagDefine.FValue, GrpcMessageField fieldWithMeta = null)
        {
            if (field.FieldDesc.Type == FieldDescriptorProto.Types.Type.String)
            {
                var checkField = fieldWithMeta ?? field;
                var tempField = ProtoCommentParser.ProcessMetaString(checkField.FieldDesc, tag, getField);
                return $"(const char*)StringCast<UTF8CHAR>(*({tempField})).Get()";
            }
            else if (field.FieldDesc.Type == FieldDescriptorProto.Types.Type.Bytes)
            {
                return $"std::string((const char*)({getField}.Value.GetData()), (size_t){getField}.Value.Num())";
            }
            else if (field.FieldDesc.Type == FieldDescriptorProto.Types.Type.Enum)
            {
                return $"{field.FieldGrpcType}(static_cast<uint8>({getField}))";
            }
            else if (field.FieldDesc.Type == FieldDescriptorProto.Types.Type.Float)
            {
                if (ProtoCommentParser.FindFieldMeta(field.FieldDesc, CommentTagDefine.RoundToFloat, out var v))
                {
                    if(v == "false") return getField;                    
                }
                // 所有float都转
                return $"FTurboLinkGrpcMessageUtil::RoundToFloat({getField})";
            }
            
            return getField;
        }

        private void GenerateMessageMarshalingDefine(StringBuilder sb, GrpcMessage message)
        {
            if (ProtoCommentParser.FindMessageMeta(message.MessageDesc, CommentTagDefine.ExportConvertFunctionImplement, out var v))
            {
                // 不导出实现函数
                if (v.ToLower() == "false") return;
            }
            
            // ---------- GRPC_TO_TURBOLINK ----------
            sb.AppendLine($"void GRPC_TO_TURBOLINK(const ::{message.GrpcName}* in, {message.Name}* out)");
            sb.AppendLine("{");

            foreach (GrpcMessageField field in message.Fields)
            {
                if (field is GrpcMessageField_Map mapField)
                {
                    sb.AppendLine($"    out->{mapField.FieldName}.Empty(in->{mapField.FieldGrpcName}_size());");
                    sb.AppendLine($"    for (const auto& item : in->{mapField.FieldGrpcName}())");
                    sb.AppendLine("    {");

                    if (field.NeedNativeMake)
                    {
                        sb.AppendLine($"        {mapField.ValueField.FieldType} field;");
                        sb.AppendLine($"        GRPC_TO_TURBOLINK(&item.second, &field);");
                        sb.AppendLine(
                            $"        out->{mapField.FieldName}.Add(StringCast<TCHAR>((const UTF8CHAR*)item.first.c_str()).Get(), MakeShareable(new {mapField.ValueField.FieldType}(field)));");
                    }
                    else
                    {
                        var keyExpr = ConvertFieldFromGrpcToTurboLink(mapField.KeyField, "item.first");
                        sb.AppendLine($"        auto& value = out->{mapField.FieldName}.Add({keyExpr});");

                        if (mapField.ValueField.FieldDesc.Type == FieldDescriptorProto.Types.Type.Message)
                        {
                            sb.AppendLine($"        GRPC_TO_TURBOLINK(&item.second, &value);");
                        }
                        else
                        {
                            var valExpr = ConvertFieldFromGrpcToTurboLink(mapField.ValueField, "item.second");
                            sb.AppendLine($"        value = {valExpr};");
                        }
                    }

                    sb.AppendLine("    }");
                }
                else if (field is GrpcMessageField_Repeated repeatedField)
                {
                    sb.AppendLine($"    out->{repeatedField.FieldName}.Empty(in->{repeatedField.FieldGrpcName}_size());");
                    sb.AppendLine($"    for (int i=0; i<in->{repeatedField.FieldGrpcName}_size(); ++i)");
                    sb.AppendLine("    {");

                    if (field.NeedNativeMake)
                    {
                        sb.AppendLine($"        {repeatedField.ItemField.FieldType} field;");
                        sb.AppendLine($"        GRPC_TO_TURBOLINK(&(in->{repeatedField.FieldGrpcName}(i)), &field);");
                        sb.AppendLine($"        out->{repeatedField.FieldName}.Add(MakeShareable(new {repeatedField.ItemField.FieldType}(field)));");
                    }
                    else if (field.FieldDesc.Type == FieldDescriptorProto.Types.Type.Message)
                    {
                        sb.AppendLine($"        GRPC_TO_TURBOLINK(&(in->{repeatedField.FieldGrpcName}(i)), &(out->{repeatedField.FieldName}.AddZeroed_GetRef()));");
                    }
                    else
                    {
                        var getField = $"in->{repeatedField.FieldGrpcName}(i)";
                        var valExpr = ConvertFieldFromGrpcToTurboLink(repeatedField.ItemField, getField);
                        sb.AppendLine($"        out->{repeatedField.FieldName}.Add({valExpr});");
                    }

                    sb.AppendLine("    }");
                }
                else if (field is GrpcMessageField_Oneof oneofField)
                {
                    var oneofMessage = oneofField.OneofMessage;
                    sb.AppendLine($"    switch(in->{oneofMessage.GrpcName}_case())");
                    sb.AppendLine("    {");
                    foreach (GrpcMessageField fieldOfOneofMessage in oneofMessage.Fields)
                    {
                        sb.AppendLine($"    case ::{message.GrpcName}::k{fieldOfOneofMessage.FieldName}:");
                        if (fieldOfOneofMessage.NeedNativeMake)
                        {
                            sb.AppendLine("    {");
                            sb.AppendLine($"        {fieldOfOneofMessage.FieldType} field;");
                            sb.AppendLine($"        GRPC_TO_TURBOLINK(&(in->{fieldOfOneofMessage.FieldGrpcName}()), &field);");
                            sb.AppendLine($"        out->{field.FieldName}.{fieldOfOneofMessage.FieldName}=MakeShareable(new {fieldOfOneofMessage.FieldType}(field));");
                            sb.AppendLine($"        out->{field.FieldName}.{field.FieldName}Case = {((GrpcMessage_Oneof)oneofMessage).OneofEnum.Name}::{fieldOfOneofMessage.FieldName};");
                            sb.AppendLine("    }");
                        }
                        else if (fieldOfOneofMessage.FieldDesc.Type == FieldDescriptorProto.Types.Type.Message)
                        {
                            sb.AppendLine($"        GRPC_TO_TURBOLINK(&(in->{fieldOfOneofMessage.FieldGrpcName}()), &(out->{field.FieldName}.{fieldOfOneofMessage.FieldName}));");
                            sb.AppendLine($"        out->{field.FieldName}.{field.FieldName}Case = {((GrpcMessage_Oneof)oneofMessage).OneofEnum.Name}::{fieldOfOneofMessage.FieldName};");
                        }
                        else
                        {
                            var getField = $"in->{fieldOfOneofMessage.FieldGrpcName}()";
                            var valExpr = ConvertFieldFromGrpcToTurboLink(fieldOfOneofMessage, getField);
                            sb.AppendLine($"        out->{field.FieldName}.{fieldOfOneofMessage.FieldName}={valExpr};");
                            sb.AppendLine($"        out->{field.FieldName}.{field.FieldName}Case = {((GrpcMessage_Oneof)oneofMessage).OneofEnum.Name}::{fieldOfOneofMessage.FieldName};");
                        }

                        sb.AppendLine("    break;");
                    }
                    sb.AppendLine("    }");
                }
                else
                {
                    if (field.NeedNativeMake)
                    {
                        sb.AppendLine("    {");
                        sb.AppendLine($"        {field.FieldType} field;");
                        sb.AppendLine($"        GRPC_TO_TURBOLINK(&(in->{field.FieldGrpcName}()), &field);");
                        sb.AppendLine($"        out->{field.FieldName} = MakeShareable(new {field.FieldType}(field));");
                        sb.AppendLine("    }");
                    }
                    else if (field.FieldDesc.Type == FieldDescriptorProto.Types.Type.Message)
                    {
                        sb.AppendLine($"    GRPC_TO_TURBOLINK(&(in->{field.FieldGrpcName}()), &(out->{field.FieldName}));");
                    }
                    else
                    {
                        var getField = $"in->{field.FieldGrpcName}()";
                        var valExpr = ConvertFieldFromGrpcToTurboLink(field, getField);
                        sb.AppendLine($"    out->{field.FieldName}={valExpr};");
                    }
                }
            }

            sb.AppendLine("}");
            sb.AppendLine();

            // ---------- TURBOLINK_TO_GRPC ----------
            sb.AppendLine($"void TURBOLINK_TO_GRPC(const {message.Name}* in, ::{message.GrpcName}* out)");
            sb.AppendLine("{");

            foreach (GrpcMessageField field in message.Fields)
            {
                var fieldsetName = $"set_{field.FieldGrpcName}";

                if (field is GrpcMessageField_Map mapField)
                {
                    sb.AppendLine($"    for (const auto& item : in->{mapField.FieldName})");
                    sb.AppendLine("    {");
                    if (field.NeedNativeMake)
                    {
                        sb.AppendLine($"        {mapField.ValueField.FieldGrpcType} value;");
                        sb.AppendLine($"        TURBOLINK_TO_GRPC(item.Value.Get(), &value);");
                        var keyExpr = ConvertFieldFromTurboLinkToGrpc(mapField.KeyField, "item.Key", CommentTagDefine.FMapKey, field);
                        sb.AppendLine($"        (*(out->mutable_{mapField.FieldGrpcName}()))[{keyExpr}] = value;");
                    }
                    else if (mapField.ValueField.FieldDesc.Type == FieldDescriptorProto.Types.Type.Message)
                    {
                        sb.AppendLine($"        {mapField.ValueField.FieldGrpcType} value;");
                        sb.AppendLine($"        TURBOLINK_TO_GRPC(&item.Value, &value);");
                        var keyExpr = ConvertFieldFromTurboLinkToGrpc(mapField.KeyField, "item.Key", CommentTagDefine.FMapKey, field);
                        sb.AppendLine($"        (*(out->mutable_{mapField.FieldGrpcName}()))[{keyExpr}] = value;");
                    }
                    else
                    {
                        var keyExpr = ConvertFieldFromTurboLinkToGrpc(mapField.KeyField, "item.Key", CommentTagDefine.FMapKey, field);
                        var valExpr = ConvertFieldFromTurboLinkToGrpc(mapField.ValueField, "item.Value", CommentTagDefine.FMapValue, field);
                        sb.AppendLine($"        (*(out->mutable_{mapField.FieldGrpcName}()))[{keyExpr}] = {valExpr};");
                    }

                    sb.AppendLine("    }");
                }
                else if (field is GrpcMessageField_Repeated)
                {
                    sb.AppendLine($"    for(const auto& value : in->{field.FieldName})");
                    sb.AppendLine("    {");
                    if (field.NeedNativeMake)
                    {
                        sb.AppendLine($"        TURBOLINK_TO_GRPC(value.Get(), out->add_{field.FieldGrpcName}());");
                    }
                    else if (field.FieldDesc.Type == FieldDescriptorProto.Types.Type.Message)
                    {
                        sb.AppendLine($"        TURBOLINK_TO_GRPC(&value, out->add_{field.FieldGrpcName}());");
                    }
                    else
                    {
                        var valExpr = ConvertFieldFromTurboLinkToGrpc(field, "value", CommentTagDefine.FArrayValue, field);
                        sb.AppendLine($"        out->add_{field.FieldGrpcName}({valExpr});");
                    }
                    sb.AppendLine("    }");
                }
                else if (field is GrpcMessageField_Oneof oneofField)
                {
                    var oneofMessage = oneofField.OneofMessage;
                    sb.AppendLine($"    switch (in->{field.FieldName}.{field.FieldName}Case)");
                    sb.AppendLine("    {");
                    foreach (GrpcMessageField fieldOfOneofMessage in oneofMessage.Fields)
                    {
                        var getField = $"in->{field.FieldName}.{fieldOfOneofMessage.FieldName}";
                        sb.AppendLine($"    case {((GrpcMessage_Oneof)oneofMessage).OneofEnum.Name}::{fieldOfOneofMessage.FieldName}:");
                        if (fieldOfOneofMessage.NeedNativeMake)
                        {
                            sb.AppendLine($"        TURBOLINK_TO_GRPC({getField}.Get(), out->mutable_{fieldOfOneofMessage.FieldGrpcName}());");
                        }
                        else if (fieldOfOneofMessage.FieldDesc.Type == FieldDescriptorProto.Types.Type.Message)
                        {
                            sb.AppendLine($"        TURBOLINK_TO_GRPC(&({getField}), out->mutable_{fieldOfOneofMessage.FieldGrpcName}());");
                        }
                        else
                        {
                            var valExpr = ConvertFieldFromTurboLinkToGrpc(fieldOfOneofMessage, getField, CommentTagDefine.FOneofValue, field);
                            sb.AppendLine($"        out->set_{fieldOfOneofMessage.FieldGrpcName}({valExpr});");
                        }

                        sb.AppendLine("        break;");
                    }
                    sb.AppendLine("    }");
                }
                else
                {
                    if (field.NeedNativeMake)
                    {
                        sb.AppendLine($"    TURBOLINK_TO_GRPC(in->{field.FieldName}.Get(), out->mutable_{field.FieldGrpcName}());");
                    }
                    else if (field.FieldDesc.Type == FieldDescriptorProto.Types.Type.Message)
                    {
                        sb.AppendLine($"    TURBOLINK_TO_GRPC(&(in->{field.FieldName}), out->mutable_{field.FieldGrpcName}());");
                    }
                    else
                    {
                        var getField = $"in->{field.FieldName}";
                        var valExpr = ConvertFieldFromTurboLinkToGrpc(field, getField);
                        sb.AppendLine($"    out->{fieldsetName}({valExpr});");
                    }
                }
            }

            sb.AppendLine("}");
        }
    }
}