using System.IO;
using System.CodeDom.Compiler;

namespace protoc_gen_turbolink.Template
{
    public class MarshalingH
    {
        private readonly GrpcServiceFile s;
        private readonly GenerateParam g;

        public MarshalingH(GrpcServiceFile _s, GenerateParam _g)
        {
            s = _s;
            g = _g;
        }

        public string TransformText()
        {
            using (var sw = new StringWriter())
            using (var writer = new IndentedTextWriter(sw, "\t"))
            {
                // 1. 文件头声明
                if (!g.SingleOutputFile)
                {
                    writer.WriteLine("//Generated by TurboLink CodeGenerator, do not edit!");
                    writer.WriteLine("#pragma once");
                    writer.WriteLine($"#include \"{s.TurboLinkBasicFileName}Message.h\"");

                    // 2. 条件包含逻辑
                    if (g.GenerateServiceCode)
                    {
                        writer.WriteLine("#include \"TurboLinkGrpcContext.h\"");
                    }

                    if (g.GenerateServiceCode && s.ServiceArray.Count > 0)
                    {
                        // 2026年推荐使用 Path.ChangeExtension 替代手动字符串拼接
                        string grpcHeader = Path.ChangeExtension(s.FileName, "grpc.pb.h");
                        writer.WriteLine($"#include \"{grpcHeader}\"");
                    }
                    else
                    {
                        string pbHeader = Path.ChangeExtension(s.FileName, "pb.h");
                        writer.WriteLine($"#include \"{pbHeader}\"");
                    }

                    writer.WriteLine();
                }

                // 3. 消息转换函数声明 (Marshaling Functions)
                foreach (var message in s.MessageArray)
                {
                    // T4 中的 if(message is GrpcMessage_Oneof) continue;
                    if (message is GrpcMessage_Oneof) continue;

                    writer.WriteLine($"void GRPC_TO_TURBOLINK(const ::{message.GrpcName}* in, {message.Name}* out);");
                    writer.WriteLine($"void TURBOLINK_TO_GRPC(const {message.Name}* in, ::{message.GrpcName}* out);");
                    writer.WriteLine();
                }

                // 4. 服务相关的类型定义 (Typedefs for Reader/Writer)
                if (g.GenerateServiceCode)
                {
                    foreach (var service in s.ServiceArray)
                    {
                        foreach (var method in service.MethodArray)
                        {
                            GenerateReaderWriterTypedef(writer, service, method);
                        }
                    }
                }

                return sw.ToString();
            }
        }

        /// <summary>
        /// 生成针对不同 gRPC 模式的异步读写器 Typedef
        /// </summary>
        private void GenerateReaderWriterTypedef(IndentedTextWriter writer, GrpcService service, GrpcServiceMethod method)
        {
            string typedefName = $"{service.Name}_{method.Name}_ReaderWriter";
            string grpcType;

            // 根据流模式确定 gRPC 原生类
            if (method.ClientStreaming && method.ServerStreaming)
            {
                // 双向流
                grpcType = $"grpc::ClientAsyncReaderWriter<{method.GrpcInputType}, {method.GrpcOutputType}>";
            }
            else if (method.ClientStreaming && !method.ServerStreaming)
            {
                // 客户端流
                grpcType = $"grpc::ClientAsyncWriter<{method.GrpcInputType}>";
            }
            else if (!method.ClientStreaming && method.ServerStreaming)
            {
                // 服务端流
                grpcType = $"grpc::ClientAsyncReader<{method.GrpcOutputType}>";
            }
            else
            {
                // 普通 Unary 调用
                grpcType = $"grpc::ClientAsyncResponseReader<{method.GrpcOutputType}>";
            }

            writer.WriteLine($"typedef {grpcType} {typedefName};");
        }
    }
}
