using System.IO;
using System.CodeDom.Compiler;

namespace protoc_gen_turbolink.Template
{
    public class MessageCPP
    {
        private readonly GrpcServiceFile s;
        private readonly GenerateParam g;

        public MessageCPP(GrpcServiceFile _s, GenerateParam _g)
        {
            s = _s;
            g = _g;
        }

        public string TransformText()
        {
            using (var sw = new StringWriter())
            using (var writer = new IndentedTextWriter(sw, "    "))
            {
                writer.WriteLine("//Generated by TurboLink CodeGenerator, do not edit!");
                writer.WriteLine($"#include \"{s.TurboLinkBasicFileName}Message.h\"");

                // 1. JSON 支持逻辑
                if (g.GenerateJsonCode)
                {
                    writer.WriteLine($"#include \"{s.TurboLinkBasicFileName}Marshaling.h\"");
                    writer.WriteLine("#include \"google/protobuf/util/json_util.h\"");
                    writer.WriteLine();

                    foreach (var message in s.MessageArray)
                    {
                        if (message is not GrpcMessage_Oneof)
                        {
                            writer.WriteLine($"DEFINE_JSON_FUNCTIONS({message.Name}, ::{message.GrpcName})");
                        }
                    }
                }

                // 2. 遍历消息生成 HelperLibrary 实现
                if (g.GenerateBPHelper)
                {
                    foreach (var message in s.MessageArray)
                    {
                        if (message.HasNativeMake || message is GrpcMessage_Oneof)
                        {
                            GenerateMakeFunction(writer, message);
                            GenerateBreakFunction(writer, message);
                        }
                    }
                }

                return sw.ToString();
            }
        }

        private void GenerateMakeFunction(IndentedTextWriter writer, GrpcMessage message)
        {
            writer.WriteLine();
            string helperClass = $"U{message.Name.Substring(1)}HelperLibrary";
            writer.Write($"{message.Name} {helperClass}::Make{message.CamelName}(");

            // 生成参数列表 (复用逻辑)
            WriteFunctionParams(writer, message, isReference: false);
            writer.WriteLine(")");

            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"{message.Name} {message.CamelName};");

            if (message is GrpcMessage_Oneof oneof)
            {
                writer.WriteLine($"{message.CamelName}.{oneof.CamelName}Case = {oneof.CamelName}Case;");
            }

            foreach (var field in message.Fields)
            {
                if (field.NeedNativeMake)
                {
                    GenerateMakeFieldLogic(writer, message, field);
                }
                else
                {
                    writer.WriteLine($"{message.CamelName}.{field.FieldName} = {field.FieldName};");
                }
            }

            writer.WriteLine();
            writer.WriteLine($"return {message.CamelName};");
            writer.Indent--;
            writer.WriteLine("}");
        }

        private void GenerateBreakFunction(IndentedTextWriter writer, GrpcMessage message)
        {
            writer.WriteLine();
            string helperClass = $"U{message.Name.Substring(1)}HelperLibrary";
            writer.Write($"void {helperClass}::Break{message.CamelName}(const {message.Name}& {message.CamelName}, ");

            // 生成参数列表 (复用逻辑，Break 函数使用引用)
            WriteFunctionParams(writer, message, isReference: true);
            writer.WriteLine(")");

            writer.WriteLine("{");
            writer.Indent++;

            if (message is GrpcMessage_Oneof oneof)
            {
                writer.WriteLine($"{oneof.CamelName}Case = {message.CamelName}.{oneof.CamelName}Case;");
            }

            foreach (var field in message.Fields)
            {
                if (field.NeedNativeMake)
                {
                    GenerateBreakFieldLogic(writer, message, field);
                }
                else
                {
                    writer.WriteLine($"{field.FieldName} = {message.CamelName}.{field.FieldName};");
                }
            }

            writer.Indent--;
            writer.WriteLine("}");
        }

        private void GenerateMakeFieldLogic(IndentedTextWriter writer, GrpcMessage message, GrpcMessageField field)
        {
            if (field is GrpcMessageField_Map mapField)
            {
                writer.WriteLine($"for (const auto& element : {field.FieldName})");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"{message.CamelName}.{field.FieldName}.Add(element.Key, MakeShareable(new {mapField.ValueField.FieldType}(element.Value)));");
                writer.Indent--;
                writer.WriteLine("}");
            }
            else if (field is GrpcMessageField_Repeated repeatedField)
            {
                writer.WriteLine($"for (const auto& element : {field.FieldName})");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"{message.CamelName}.{field.FieldName}.Add(MakeShareable(new {repeatedField.ItemField.FieldType}(element)));");
                writer.Indent--;
                writer.WriteLine("}");
            }
            else
            {
                writer.WriteLine($"{message.CamelName}.{field.FieldName} = MakeShareable(new {field.FieldType}({field.FieldName}));");
            }
        }

        private void GenerateBreakFieldLogic(IndentedTextWriter writer, GrpcMessage message, GrpcMessageField field)
        {
            if (field is GrpcMessageField_Map)
            {
                writer.WriteLine($"for (auto& element : {message.CamelName}.{field.FieldName})");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"{field.FieldName}.Add(element.Key, *(element.Value.Get()));");
                writer.Indent--;
                writer.WriteLine("}");
            }
            else if (field is GrpcMessageField_Repeated)
            {
                writer.WriteLine($"for (auto& element : {message.CamelName}.{field.FieldName})");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"{field.FieldName}.Add(*(element.Get()));");
                writer.Indent--;
                writer.WriteLine("}");
            }
            else
            {
                writer.WriteLine($"if({message.CamelName}.{field.FieldName}.Get())");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"{field.FieldName} = *({message.CamelName}.{field.FieldName}.Get());");
                writer.Indent--;
                writer.WriteLine("}");
            }
        }

        private void WriteFunctionParams(IndentedTextWriter writer, GrpcMessage message, bool isReference)
        {
            bool isFirst = true;
            if (message is GrpcMessage_Oneof oneof)
            {
                string suffix = isReference ? "&" : "";
                writer.Write($"{oneof.OneofEnum.Name}{suffix} {oneof.CamelName}Case");
                isFirst = false;
            }

            for (int i = 0; i < message.Fields.Count; i++)
            {
                var field = message.Fields[i];
                if (!isFirst) writer.Write(", ");
                if (!isFirst && i % 3 == 0) writer.Write("\n    ");

                string suffix = isReference ? "&" : "";
                writer.Write($"{field.FieldType}{suffix} {field.FieldName}");
                isFirst = false;
            }
        }
    }
}
