using System;
using System.IO;
using System.CodeDom.Compiler;
using Microsoft.CodeAnalysis;

namespace protoc_gen_turbolink.Template
{
    public partial class MessageH
    {
        private readonly GrpcServiceFile s;
        private readonly GenerateParam g;

        public MessageH(GrpcServiceFile _s, GenerateParam _g)
        {
            s = _s;
            g = _g;
        }

        public string TransformText()
        {
            using (var sw = new StringWriter())
            using (var writer = new IndentedTextWriter(sw, "    ")) // 自动处理缩进
            {
                if (!g.SingleOutputFile)
                {
                    writer.WriteLine("//Generated by TurboLink CodeGenerator, do not edit!");
                    writer.WriteLine("#pragma once");
                    writer.WriteLine("#include \"TurboLinkGrpcMessage.h\"");

                    foreach (var dependency in s.DependencyFiles)
                    {
                        writer.WriteLine($"#include \"{dependency.TurboLinkBasicFileName}Message.h\"");
                    }

                    if (s.EnumArray.Count > 0 || s.MessageArray.Count > 0)
                    {
                        if (g.GenerateBPHelper && s.NeedBlueprintFunctionLibrary())
                            writer.WriteLine("#include \"Kismet/BlueprintFunctionLibrary.h\"");

                        writer.WriteLine($"#include \"{s.CamelFileName}Message.generated.h\"");
                    }
                }

                // 渲染 Enum
                GenerateEnums(writer);

                // 渲染 Structs
                GenerateStructs(writer);

                // 渲染 Helper Libraries
                if (g.GenerateBPHelper)
                {
                    GenerateHelpers(writer);
                }

                return sw.ToString();
            }
        }

        private void GenerateEnums(IndentedTextWriter writer)
        {
            foreach (var enumDefine in s.EnumArray)
            {
                writer.WriteLine();
                // writer.WriteLine($"UENUM(BlueprintType, meta = (DisplayName=\"{enumDefine.DisplayName}\", ScriptName=\"{enumDefine.Name}\"))");
                writer.WriteLine($"UENUM(BlueprintType, meta = (DisplayName=\"{enumDefine.OriginalDisplayName}\", ScriptName=\"{enumDefine.Name}\"))");
                writer.WriteLine($"enum class {enumDefine.Name} : uint8");
                writer.WriteLine("{");
                writer.Indent++;

                if (enumDefine.MissingZeroField)
                    writer.WriteLine("_ZERO_RESERVED_FIELD_=0 UMETA(Hidden),");

                foreach (var enumField in enumDefine.Fields)
                    writer.WriteLine($"{enumField.Name}={enumField.Number},");

                writer.Indent--;
                writer.WriteLine("};");
            }
        }

        private void GenerateStructs(IndentedTextWriter writer)
        {
            foreach (var message in s.MessageArray)
            {
                writer.WriteLine();
                if (g.GenerateBPHelper && (message.HasNativeMake || message is GrpcMessage_Oneof))
                {
                    // writer.WriteLine($"USTRUCT(BlueprintType, meta = (DisplayName=\"{message.DisplayName}\",");
                    writer.WriteLine($"USTRUCT(BlueprintType, meta = (DisplayName=\"{message.OriginalDisplayName}\",");
                    writer.Indent++;
                    writer.WriteLine($"HasNativeMake = \"/Script/TurboLinkGrpc.{message.Name.Substring(1)}HelperLibrary.Make{message.CamelName}\",");
                    writer.WriteLine($"HasNativeBreak = \"/Script/TurboLinkGrpc.{message.Name.Substring(1)}HelperLibrary.Break{message.CamelName}\"))");
                    writer.Indent--;
                }
                else
                {
                    // writer.WriteLine($"USTRUCT(BlueprintType, meta = (DisplayName=\"{message.DisplayName}\"))");
                    writer.WriteLine($"USTRUCT(BlueprintType, meta = (DisplayName=\"{message.OriginalDisplayName}\"))");
                }

                writer.WriteLine($"struct {g.ExportPrefix} {message.Name} : public FPBMessage");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine("GENERATED_BODY()");
                
                if (g.GenerateDefaultFunctionCode && message is not GrpcMessage_Oneof)
                    writer.WriteLine("DECLARE_PB_DEFAULT_FUNCTIONS()");

                if (message is GrpcMessage_Oneof oneof)
                {
                    writer.WriteLine();
                    writer.WriteLine("UPROPERTY(BlueprintReadWrite, Category = TurboLink)");
                    writer.WriteLine($"{oneof.OneofEnum.Name} {oneof.CamelName}Case{{}};");
                    // Console.WriteLine($"build oneof {oneof.OneofEnum.Name} {oneof.CamelName}");
                }

                MessageInfo messageTagInfo = null;
                if(message.MessageDesc != null) s.CommentParser.MessageInfos.TryGetValue(message.MessageDesc, out messageTagInfo);
                
                foreach (var field in message.Fields)
                {
                    writer.WriteLine();
                    if (field.NeedNativeMake)
                    {
                        writer.WriteLine($"{field.TypeAsNativeField} {field.FieldName};");
                    }
                    else
                    {
                        FieldInfoEx exInfo = null;
                        if (messageTagInfo != null) messageTagInfo.Fields.TryGetValue(field.FieldDesc, out exInfo);
                        var tagInfo = exInfo?.TagInfos.Find((TagInfo info) =>
                        {
                            return info.Tag == "BlueprintReadWrite";
                        });
                        bool enableBlueprintReadWrite = tagInfo == null || tagInfo.Info.ToLower() != "false";
                        if (enableBlueprintReadWrite)
                        {
                            writer.WriteLine("UPROPERTY(BlueprintReadWrite, Category = TurboLink)");
                        }
                        else
                        {
                            writer.WriteLine("UPROPERTY(Category = TurboLink)");
                        }
                        writer.WriteLine($"{field.FieldType} {field.FieldName}{field.FieldDefaultValue};");
                    }
                }

                if (messageTagInfo != null)
                {
                    writer.WriteLine();
                    foreach(var tagInfo in messageTagInfo.TagInfos)
                    {
                        if (tagInfo.Tag == "add")
                        {
                            writer.WriteLine(tagInfo.Info.Replace("_UESTRUCT", message.Name));
                        }
                    }
                }
                
                writer.Indent--;
                writer.WriteLine("};");
            }
        }

        private void GenerateHelpers(IndentedTextWriter writer)
        {
            foreach (var message in s.MessageArray)
            {
                // 仅针对有 NativeMake 或 Oneof 的消息生成 HelperLibrary
                if (!(message.HasNativeMake || message is GrpcMessage_Oneof)) continue;

                writer.WriteLine();
                writer.WriteLine("UCLASS()");
                // 去掉开头的 'F' 前缀（假设消息名如 FMyMessage），在 UClass 名中使用 MyMessageHelperLibrary
                string libraryName = $"U{message.Name.Substring(1)}HelperLibrary";
                writer.WriteLine($"class {g.ExportPrefix} {libraryName} : public UBlueprintFunctionLibrary");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine("GENERATED_BODY()");
                
                writer.Indent--;
                writer.WriteLine("public:");
                writer.Indent++;
                
                // --- 1. Make 函数 ---
                writer.WriteLine("UFUNCTION(BlueprintPure, Category = \"TurboLink|" + s.CamelPackageName + "\", meta=(BlueprintThreadSafe))");
                writer.Write($"static {message.Name} Make{message.CamelName}(");
                
                // 参数列表处理
                WriteFunctionParameters(writer, message, isReference: false);
                writer.WriteLine(");");

                writer.WriteLine();

                // --- 2. Break 函数 ---
                writer.WriteLine("UFUNCTION(BlueprintPure, Category = \"TurboLink|" + s.CamelPackageName + "\", meta=(BlueprintThreadSafe))");
                writer.Write($"static void Break{message.CamelName}(const {message.Name}& {message.CamelName}, ");
                
                // 参数列表处理 (Break 函数参数均为引用)
                WriteFunctionParameters(writer, message, isReference: true);
                writer.WriteLine(");");

                writer.Indent--;
                writer.WriteLine("};");
            }
        }

        /// <summary>
        /// 通用的参数列表生成器
        /// </summary>
        private void WriteFunctionParameters(IndentedTextWriter writer, GrpcMessage message, bool isReference)
        {
            writer.Indent++;
            
            // 如果是 Oneof，增加 Case 枚举参数
            bool isFirst = true;
            if (message is GrpcMessage_Oneof oneofMessage)
            {
                string refSymbol = isReference ? "&" : "";
                writer.Write($"{oneofMessage.OneofEnum.Name}{refSymbol} {oneofMessage.CamelName}Case");
                isFirst = false;
            }

            for (int i = 0; i < message.Fields.Count; i++)
            {
                var field = message.Fields[i];
                
                if (!isFirst) writer.Write(", ");
                
                // 每 3 个参数换一次行，保持代码整洁 (模仿原 T4 逻辑)
                if (!isFirst && i % 3 == 0) 
                {
                    writer.WriteLine();
                }

                string refSymbol = isReference ? "&" : "";
                writer.Write($"{field.FieldType}{refSymbol} {field.FieldName}");
                
                isFirst = false;
            }

            writer.Indent--;
        }
    }
}
