using System.IO;
using System.CodeDom.Compiler;
using System.Linq;

namespace protoc_gen_turbolink.Template
{
    public class NodeH
    {
        private readonly GrpcServiceFile s;
        private readonly GenerateParam g;

        public NodeH(GrpcServiceFile _s, GenerateParam _g)
        {
            s = _s;
            g = _g;
        }

        public string TransformText()
        {
            using (var sw = new StringWriter())
            using (var writer = new IndentedTextWriter(sw, "\t"))
            {
                // 1. 文件头声明与基础包含
                writer.WriteLine("//Generated by TurboLink CodeGenerator, do not edit!");
                writer.WriteLine("#pragma once");
                writer.WriteLine("#include \"CoreMinimal.h\"");
                writer.WriteLine("#include \"Kismet/BlueprintAsyncActionBase.h\"");
                writer.WriteLine("#include \"TurboLinkGrpcClient.h\"");
                writer.WriteLine($"#include \"{s.CamelFileName}Message.h\"");

                // 只有当存在有效的异步节点方法时才包含 .generated.h
                if (s.GetTotalPingPongMethodCounts() > 0)
                {
                    writer.WriteLine($"#include \"{s.CamelFileName}Node.generated.h\"");
                }
                writer.WriteLine();

                // 2. 遍历 Service
                foreach (var service in s.ServiceArray)
                {
                    // 统计当前 Service 下支持异步节点的 Method 数量（非 ClientStreaming）
                    int pingPongMethodCounts = service.MethodArray.Count(m => !m.ClientStreaming);
                    if (pingPongMethodCounts == 0) continue;

                    // 前置声明
                    writer.WriteLine($"class U{service.Name};");
                    writer.WriteLine($"class U{service.Name}Client;");

                    // 3. 遍历 Method 生成 UClass
                    foreach (var method in service.MethodArray)
                    {
                        // 异步节点不支持客户端流式 RPC
                        if (method.ClientStreaming) continue;

                        GenerateNodeClass(writer, service, method);
                    }
                }

                return sw.ToString();
            }
        }

        private void GenerateNodeClass(IndentedTextWriter writer, GrpcService service, GrpcServiceMethod method)
        {
            string nodeClassName = $"UCall{service.Name}{method.Name}";
            string delegateName = $"F{service.Name}{method.Name}Delegate";

            writer.WriteLine();
            writer.WriteLine("UCLASS(ClassGroup = TurboLink)");
            writer.WriteLine($"class TURBOLINKGRPC_API {nodeClassName} : public UBlueprintAsyncActionBase");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("GENERATED_BODY()");

            writer.WriteLine();
            writer.WriteLine("public:");
            writer.Indent++;
            
            // 定义动态多播委托（用于蓝图引脚输出）
            writer.WriteLine($"DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams({delegateName}, const FGrpcResult&, GrpcResult, const {method.OutputType}&, Response);");
            writer.WriteLine();

            // 静态工厂函数声明（蓝图节点入口）
            writer.WriteLine("UFUNCTION(BlueprintCallable, Category = \"TurboLink|" + service.Name + "\", meta = (");
            writer.Indent++;
            writer.WriteLine("BlueprintInternalUseOnly = \"true\",");
            writer.WriteLine("WorldContext = \"WorldContextObject\",");
            writer.WriteLine($"DisplayName = \"Call {service.Name} {method.Name}\",");
            writer.WriteLine("AdvancedDisplay = 2))");
            writer.Indent--;
            writer.WriteLine($"static {nodeClassName}* {method.Name}(UObject* WorldContextObject, const {method.InputType}& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);");
            writer.WriteLine();

            // 蓝图输出执行引脚 (Pins)
            writer.WriteLine("UPROPERTY(BlueprintAssignable)");
            writer.WriteLine($"{delegateName} On{method.Name}Response;");
            writer.WriteLine();

            if (method.ServerStreaming)
            {
                writer.WriteLine("UPROPERTY(BlueprintAssignable)");
                writer.WriteLine($"{delegateName} OnFinished;");
                writer.WriteLine();
            }

            writer.WriteLine("UPROPERTY(BlueprintAssignable)");
            writer.WriteLine($"{delegateName} OnFail;");
            writer.Indent--;

            writer.WriteLine();
            writer.WriteLine("private:");
            writer.Indent++;
            writer.WriteLine("virtual void Activate() override;");
            writer.WriteLine();

            // 成员变量（引用相关的 Service 和 Client）
            writer.WriteLine("UPROPERTY()");
            writer.WriteLine($"U{service.Name}* {service.Name};");
            writer.WriteLine();
            writer.WriteLine("UPROPERTY()");
            writer.WriteLine($"U{service.Name}*Client {service.Name}Client;");
            writer.WriteLine();

            writer.WriteLine("FGrpcContextHandle Context;");
            writer.WriteLine($"{method.InputType} Request;");
            writer.WriteLine("EGrpcServiceState ServiceState;");
            writer.WriteLine("FGrpcMetaData MetaData;");
            writer.WriteLine("float DeadLineSeconds;");
            writer.WriteLine();

            // 内部回调函数
            writer.WriteLine("UFUNCTION()");
            writer.WriteLine("void OnServiceStateChanged(EGrpcServiceState NewState);");
            writer.WriteLine();
            writer.WriteLine("UFUNCTION()");
            writer.WriteLine("void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);");
            writer.WriteLine();
            writer.WriteLine("UFUNCTION()");
            writer.WriteLine($"void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const {method.OutputType}& Response);");
            writer.WriteLine();
            writer.WriteLine("void Shutdown();");

            writer.Indent--; // End Private
            writer.Indent--; // End Class
            writer.WriteLine("};");
        }
    }
}
