using System.IO;
using System.CodeDom.Compiler;

namespace protoc_gen_turbolink.Template
{
    public class NodeCPP
    {
        private readonly GrpcServiceFile s;
        private readonly GenerateParam g;

        public NodeCPP(GrpcServiceFile _s, GenerateParam _g)
        {
            s = _s;
            g = _g;
        }

        public string TransformText()
        {
            using (var sw = new StringWriter())
            using (var writer = new IndentedTextWriter(sw, "\t"))
            {
                // 1. 写入头文件包含
                writer.WriteLine("//Generated by TurboLink CodeGenerator, do not edit!");
                writer.WriteLine($"#include \"{s.TurboLinkBasicFileName}Node.h\"");
                writer.WriteLine($"#include \"{s.TurboLinkBasicFileName}Service.h\"");
                writer.WriteLine("#include \"TurboLinkGrpcManager.h\"");
                writer.WriteLine("#include \"TurboLinkGrpcUtilities.h\"");
                writer.WriteLine("#include \"Engine/World.h\"");
                writer.WriteLine("#include \"TimerManager.h\"");
                writer.WriteLine("#include \"Runtime/Launch/Resources/Version.h\"");

                // 2. 遍历 Service 和 Method
                foreach (var service in s.ServiceArray)
                {
                    foreach (var method in service.MethodArray)
                    {
                        // 异步节点仅支持非客户端流（Unary 或 Server Streaming）
                        if (method.ClientStreaming) continue;

                        GenerateNodeImplementation(writer, service, method);
                    }
                }

                return sw.ToString();
            }
        }

        private void GenerateNodeImplementation(IndentedTextWriter writer, GrpcService service, GrpcServiceMethod method)
        {
            string nodeClass = $"UCall{service.Name}{method.Name}";
            string serviceName = service.Name;
            string methodName = method.Name;

            // --- 静态工厂方法: Name() ---
            writer.WriteLine();
            writer.WriteLine($"{nodeClass}* {nodeClass}::{methodName}(UObject* WorldContextObject, const {method.InputType}& request, FGrpcMetaData metaData, float deadLineSeconds)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"{nodeClass}* node = NewObject<{nodeClass}>(WorldContextObject);");
            writer.WriteLine("UTurboLinkGrpcManager* turboLinkManager = UTurboLinkGrpcUtilities::GetTurboLinkGrpcManager(WorldContextObject);");
            writer.WriteLine();
            writer.WriteLine($"node->{serviceName} = Cast<U{serviceName}>(turboLinkManager->MakeService(\"{serviceName}\"));");
            writer.WriteLine($"if (node->{serviceName} == nullptr)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("return nullptr;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine("node->ServiceState = EGrpcServiceState::Idle;");
            writer.WriteLine("node->Request = request;");
            writer.WriteLine("node->MetaData = metaData;");
            writer.WriteLine("node->DeadLineSeconds = deadLineSeconds;");
            writer.WriteLine();
            writer.WriteLine($"node->{serviceName}->OnServiceStateChanged.AddUniqueDynamic(node, &{nodeClass}::OnServiceStateChanged);");
            writer.WriteLine("return node;");
            writer.Indent--;
            writer.WriteLine("}");

            // --- Activate() ---
            writer.WriteLine();
            writer.WriteLine($"void {nodeClass}::Activate()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"{serviceName}->Connect();");
            writer.Indent--;
            writer.WriteLine("}");

            // --- OnServiceStateChanged() ---
            writer.WriteLine();
            writer.WriteLine($"void {nodeClass}::OnServiceStateChanged(EGrpcServiceState NewState)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("if (ServiceState == NewState) return;");
            writer.WriteLine("ServiceState = NewState;");
            writer.WriteLine();
            writer.WriteLine("if (NewState == EGrpcServiceState::TransientFailure)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("FGrpcResult result;");
            writer.WriteLine("result.Code = EGrpcResultCode::ConnectionFailed;");
            writer.WriteLine();
            writer.WriteLine($"{method.OutputType} response;");
            writer.WriteLine("OnFail.Broadcast(result, response);");
            writer.WriteLine();
            writer.WriteLine("Shutdown();");
            writer.WriteLine("return;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();
            writer.WriteLine("if (NewState == EGrpcServiceState::Ready)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"{serviceName}Client = {serviceName}->MakeClient();");
            writer.WriteLine($"{serviceName}Client->OnContextStateChange.AddUniqueDynamic(this, &{nodeClass}::OnContextStateChange);");
            writer.WriteLine($"{serviceName}Client->On{methodName}Response.AddUniqueDynamic(this, &{nodeClass}::OnResponse);");
            writer.WriteLine();
            writer.WriteLine($"Context = {serviceName}Client->Init{methodName}();");
            writer.WriteLine($"{serviceName}Client->{methodName}(Context, Request, MetaData, DeadLineSeconds);");
            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");

            // --- OnContextStateChange() ---
            writer.WriteLine();
            writer.WriteLine($"void {nodeClass}::OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("if (State == EGrpcContextState::Done)");
            writer.WriteLine("{");
            writer.Indent++;
            if (method.ServerStreaming)
            {
                writer.WriteLine($"OnFinished.Broadcast(FGrpcResult{{}}, {method.OutputType}{{}});");
            }
            writer.WriteLine("Shutdown();");
            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");

            // --- OnResponse() ---
            writer.WriteLine();
            writer.WriteLine($"void {nodeClass}::OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const {method.OutputType}& Response)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("if (GrpcResult.Code == EGrpcResultCode::Ok)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"On{methodName}Response.Broadcast(GrpcResult, Response);");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine("else");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("OnFail.Broadcast(GrpcResult, Response);");
            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");

            // --- Shutdown() ---
            writer.WriteLine();
            writer.WriteLine($"void {nodeClass}::Shutdown()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"{serviceName}->OnServiceStateChanged.RemoveDynamic(this, &{nodeClass}::OnServiceStateChanged);");
            writer.WriteLine($"if ({serviceName}Client != nullptr)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"{serviceName}->RemoveClient({serviceName}Client);");
            writer.WriteLine($"{serviceName}Client->Shutdown();");
            writer.WriteLine($"{serviceName}Client = nullptr;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();
            writer.WriteLine($"if ({serviceName} != nullptr)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"UTurboLinkGrpcUtilities::GetTurboLinkGrpcManager(this)->ReleaseService({serviceName});");
            writer.WriteLine($"{serviceName} = nullptr;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();
            writer.WriteLine("SetReadyToDestroy();");
            writer.WriteLine("#if ENGINE_MAJOR_VERSION>=5");
            writer.WriteLine("\tMarkAsGarbage();");
            writer.WriteLine("#else");
            writer.WriteLine("\tMarkPendingKill();");
            writer.WriteLine("#endif");
            writer.Indent--;
            writer.WriteLine("}");
        }
    }
}
