using System.IO;
using System.CodeDom.Compiler;

namespace protoc_gen_turbolink.Template
{
    public class ServicePrivateH
    {
        private readonly GrpcServiceFile s;
        private readonly GenerateParam g;

        public ServicePrivateH(GrpcServiceFile _s, GenerateParam _g)
        {
            s = _s;
            g = _g;
        }

        public string TransformText()
        {
            using (var sw = new StringWriter())
            using (var writer = new IndentedTextWriter(sw, "\t"))
            {
                // 1. 文件头包含
                writer.WriteLine("//Generated by TurboLink CodeGenerator, do not edit!");
                writer.WriteLine("#pragma once");
                writer.WriteLine();
                writer.WriteLine($"#include \"{s.TurboLinkBasicFileName}Service.h\"");
                writer.WriteLine("#include \"TurboLinkGrpcManager_Private.h\"");
                
                // 使用 Path.ChangeExtension 转换后缀
                string grpcHeader = Path.ChangeExtension(s.FileName, "grpc.pb.h");
                writer.WriteLine($"#include \"{grpcHeader}\"");

                if (s.ServiceArray.Count > 0)
                {
                    writer.WriteLine($"#include \"{s.CamelFileName}Service_Private.generated.h\"");
                }
                writer.WriteLine();

                // 2. 生成每个服务的 Private 类 (Pimpl 模式)
                foreach (var service in s.ServiceArray)
                {
                    writer.WriteLine($"class U{service.Name}::Private");
                    writer.WriteLine("{");
                    writer.WriteLine("public:");
                    writer.Indent++;
                    writer.WriteLine("std::shared_ptr<UTurboLinkGrpcManager::Private::ServiceChannel> Channel;");
                    writer.WriteLine($"std::unique_ptr<::{s.GrpcPackageName}::{service.Name}::Stub> Stub;");
                    writer.Indent--;
                    writer.WriteLine("};");
                    writer.WriteLine();
                }

                // 3. 生成每个方法的 LambdaWrapper 类
                foreach (var service in s.ServiceArray)
                {
                    foreach (var method in service.MethodArray)
                    {
                        // 仅针对非客户端流生成 Wrapper
                        if (method.ClientStreaming) continue;

                        GenerateLambdaWrapperClass(writer, service, method);
                    }
                }

                return sw.ToString();
            }
        }

        private void GenerateLambdaWrapperClass(IndentedTextWriter writer, GrpcService service, GrpcServiceMethod method)
        {
            string className = $"U{service.Name}{method.Name}LambdaWrapper";

            writer.WriteLine("UCLASS()");
            writer.WriteLine($"class {className} : public UObject");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("GENERATED_BODY()");
            
            writer.WriteLine("public:");
            writer.Indent++;
            writer.WriteLine("UPROPERTY()");
            writer.WriteLine($"U{service.Name}Client* InnerClient;");
            writer.WriteLine();

            writer.WriteLine("UFUNCTION()");
            writer.WriteLine("void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const " + method.OutputType + "& Response);");

            if (method.ServerStreaming)
            {
                writer.WriteLine();
                writer.WriteLine("UFUNCTION()");
                writer.WriteLine("void OnContextStateChanged(FGrpcContextHandle Handle, EGrpcContextState NewState);");
            }
            writer.Indent--;

            writer.WriteLine();
            writer.WriteLine("public:");
            writer.Indent++;
            writer.WriteLine("FGrpcContextHandle Handle;");
            writer.WriteLine($"U{service.Name}::F{method.Name}ResponseLambda ResponseLambda;");

            if (method.ServerStreaming)
            {
                writer.WriteLine($"U{service.Name}::F{method.Name}FinishLambda FinishLambda;");
            }
            writer.Indent--;

            writer.Indent--;
            writer.WriteLine("};");
            writer.WriteLine();
        }
    }
}
