using System;
using System.IO;
using System.CodeDom.Compiler;

namespace protoc_gen_turbolink.Template
{
    public class ServiceCPP
    {
        private readonly GrpcServiceFile s;
        private readonly GenerateParam g;

        public ServiceCPP(GrpcServiceFile _s, GenerateParam _g)
        {
            s = _s;
            g = _g;
        }

        public string TransformText()
        {
            using (var sw = new StringWriter())
            using (var writer = new IndentedTextWriter(sw, "\t"))
            {
                // 1. 包含基础头文件
                writer.WriteLine("//Generated by TurboLink CodeGenerator, do not edit!");
                writer.WriteLine($"#include \"{s.TurboLinkBasicFileName}Service.h\"");
                writer.WriteLine($"#include \"{s.TurboLinkBasicFileName}Client.h\"");
                writer.WriteLine($"#include \"{s.CamelFileName}Service_Private.h\"");
                writer.WriteLine($"#include \"{s.CamelFileName}Marshaling.h\"");

                foreach (var dependency in s.DependencyFiles)
                {
                    writer.WriteLine($"#include \"{dependency.TurboLinkBasicFileName}Marshaling.h\"");
                }

                writer.WriteLine("#include \"TurboLinkGrpcManager_Private.h\"");
                writer.WriteLine("#include \"TurboLinkGrpcUtilities.h\"");

                // 2. 遍历 Service 实现
                foreach (var service in s.ServiceArray)
                {
                    string className = $"U{service.Name}";

                    // 构造函数与析构函数 (Pimpl 模式)
                    writer.WriteLine();
                    writer.WriteLine($"{className}::{className}()");
                    writer.WriteLine($"\t: d(new {className}::Private())");
                    writer.WriteLine("{");
                    writer.WriteLine("}");

                    writer.WriteLine();
                    writer.WriteLine($"{className}::~{className}()");
                    writer.WriteLine("{");
                    writer.Indent++;
                    writer.WriteLine("delete d;");
                    writer.Indent--;
                    writer.WriteLine("}");

                    // Connect() 实现
                    GenerateConnectMethod(writer, className, service);

                    // GetServiceState() 实现
                    GenerateStateMethod(writer, className);

                    // MakeClient() 实现
                    writer.WriteLine();
                    writer.WriteLine($"{service.Name}Client* {className}::MakeClient()");
                    writer.WriteLine("{");
                    writer.Indent++;
                    writer.WriteLine($"auto client = UGrpcService::MakeClient<{service.Name}Client>();");
                    writer.WriteLine("return client;");
                    writer.Indent--;
                    writer.WriteLine("}");

                    // Shutdown() 实现
                    GenerateShutdownMethod(writer, className);

                    // 3. 遍历 Method 生成 Lambda 调用包装
                    foreach (var method in service.MethodArray)
                    {
                        if (method.ClientStreaming) continue; // Lambda 调用不支持客户端流

                        GenerateLambdaCall(writer, className, service, method);
                    }
                }

                return sw.ToString();
            }
        }

        private void GenerateConnectMethod(IndentedTextWriter writer, string className, GrpcService service)
        {
            writer.WriteLine();
            writer.WriteLine($"void {className}::Connect()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"FString serviceEndPoint = UTurboLinkGrpcUtilities::GetTurboLinkGrpcConfig()->GetServiceEndPoint(TEXT(\"{service.Name}\"));");
            writer.WriteLine($"UE_LOG(LogTurboLink, Warning, TEXT(\"Connect to {service.Name}: '%s'\"), *serviceEndPoint);");
            writer.WriteLine();
            writer.WriteLine("if (d->Channel == nullptr) {");
            writer.Indent++;
            writer.WriteLine("d->Channel = TurboLinkManager->d->CreateServiceChannel(TCHAR_TO_UTF8(*serviceEndPoint), this);");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();
            writer.WriteLine("if (d->Stub == nullptr) {");
            writer.Indent++;
            writer.WriteLine($"d->Stub = {s.GrpcPackageName}::{service.Name}::NewStub(d->Channel->RpcChannel);");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();
            writer.WriteLine("grpc_connectivity_state currentChannelState = d->Channel->RpcChannel->GetState(true);");
            writer.WriteLine("if (OnServiceStateChanged.IsBound())");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("OnServiceStateChanged.Broadcast(UTurboLinkGrpcManager::Private::GrpcStateToServiceState(currentChannelState));");
            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");
        }

        private void GenerateStateMethod(IndentedTextWriter writer, string className)
        {
            writer.WriteLine();
            writer.WriteLine($"EGrpcServiceState {className}::GetServiceState() const");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("if (d->Channel == nullptr) return EGrpcServiceState::NotCreate;");
            writer.WriteLine();
            writer.WriteLine("auto rpcChannelState = d->Channel->RpcChannel->GetState(false);");
            writer.WriteLine("return UTurboLinkGrpcManager::Private::GrpcStateToServiceState(rpcChannelState);");
            writer.Indent--;
            writer.WriteLine("}");
        }

        private void GenerateShutdownMethod(IndentedTextWriter writer, string className)
        {
            writer.WriteLine();
            writer.WriteLine($"void {className}::Shutdown()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("Super::Shutdown();");
            writer.WriteLine("d->Stub = nullptr;");
            writer.WriteLine("if (d->Channel != nullptr) {");
            writer.Indent++;
            writer.WriteLine("TurboLinkManager->d->RemoveServiceChannel(d->Channel, this);");
            writer.WriteLine("d->Channel = nullptr;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");
        }

        private void GenerateLambdaCall(IndentedTextWriter writer, string className, GrpcService service, GrpcServiceMethod method)
        {
            writer.WriteLine();
            if (method.ServerStreaming)
            {
                writer.WriteLine($"void {className}::Call{method.Name}(const {method.InputType}& Request, F{method.Name}ResponseLambda ResponseLambda, F{method.Name}FinishLambda FinishLambda, FGrpcMetaData MetaData, float DeadLineSeconds)");
            }
            else
            {
                writer.WriteLine($"void {className}::Call{method.Name}(const {method.InputType}& Request, F{method.Name}ResponseLambda ResponseLambda, FGrpcMetaData MetaData, float DeadLineSeconds)");
            }

            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("if (InnerClient == nullptr)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("InnerClient = MakeClient();");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();
            writer.WriteLine($"{className}{method.Name}LambdaWrapper* lambdaWrapper = NewObject<{className}{method.Name}LambdaWrapper>();");
            writer.WriteLine("lambdaWrapper->InnerClient = InnerClient;");
            writer.WriteLine("lambdaWrapper->ResponseLambda = ResponseLambda;");

            if (method.ServerStreaming)
            {
                writer.WriteLine("lambdaWrapper->FinishLambda = FinishLambda;");
            }

            writer.WriteLine($"lambdaWrapper->Handle = InnerClient->Init{method.Name}();");
            writer.WriteLine($"InnerClient->On{method.Name}Response.AddUniqueDynamic(lambdaWrapper, &{className}{method.Name}LambdaWrapper::OnResponse);");

            if (method.ServerStreaming)
            {
                writer.WriteLine($"InnerClient->OnContextStateChange.AddUniqueDynamic(lambdaWrapper, &{className}{method.Name}LambdaWrapper::OnContextStateChanged);");
            }

            writer.WriteLine($"InnerClient->{method.Name}(lambdaWrapper->Handle, Request, MetaData, DeadLineSeconds);");
            writer.Indent--;
            writer.WriteLine("}");
        }
    }
}
