using System.IO;
using System.CodeDom.Compiler;

namespace protoc_gen_turbolink.Template
{
    public class ServiceH
    {
        private readonly GrpcServiceFile s;
        private readonly GenerateParam g;

        public ServiceH(GrpcServiceFile _s, GenerateParam _g)
        {
            s = _s;
            g = _g;
        }

        public string TransformText()
        {
            using (var sw = new StringWriter())
            using (var writer = new IndentedTextWriter(sw, "\t"))
            {
                // 1. 文件头声明与包含
                writer.WriteLine("//Generated by TurboLink CodeGenerator, do not edit!");
                writer.WriteLine("#pragma once");
                writer.WriteLine("#include \"TurboLinkGrpcService.h\"");
                writer.WriteLine($"#include \"{s.TurboLinkBasicFileName}Client.h\"");

                if (s.ServiceArray.Count > 0)
                {
                    writer.WriteLine($"#include \"{s.CamelFileName}Service.generated.h\"");
                    writer.WriteLine();
                    writer.WriteLine("class UTurboLinkGrpcManager;");
                }
                writer.WriteLine();

                // 2. 遍历 Service
                foreach (var service in s.ServiceArray)
                {
                    string className = $"U{service.Name}";
                    string clientClassName = $"U{service.Name}Client";

                    writer.WriteLine("UCLASS(ClassGroup = TurboLink, BlueprintType)");
                    writer.WriteLine($"class TURBOLINKGRPC_API {className} : public UGrpcService");
                    writer.WriteLine("{");
                    writer.Indent++;
                    writer.WriteLine("GENERATED_BODY()");

                    // 3. 公有基础接口
                    writer.Indent--;
                    writer.WriteLine("public:");
                    writer.Indent++;
                    writer.WriteLine("UFUNCTION(BlueprintCallable, Category = TurboLink)");
                    writer.WriteLine("virtual void Connect() override;");
                    writer.WriteLine();
                    writer.WriteLine("UFUNCTION(BlueprintCallable, Category = TurboLink)");
                    writer.WriteLine("virtual EGrpcServiceState GetServiceState() const override;");
                    writer.WriteLine();
                    writer.WriteLine("UFUNCTION(BlueprintCallable, Category = TurboLink)");
                    writer.WriteLine($"{clientClassName}* MakeClient();");
                    writer.Indent--;

                    // 4. 私有生命周期管理
                    writer.WriteLine();
                    writer.WriteLine("private:");
                    writer.Indent++;
                    writer.WriteLine("virtual void Shutdown() override;");
                    writer.WriteLine();
                    writer.WriteLine("UPROPERTY()");
                    writer.WriteLine($"{clientClassName}* InnerClient; ");
                    writer.Indent--;

                    // 5. 遍历 Method 生成 Lambda 异步接口
                    writer.WriteLine("public:");
                    writer.Indent++;
                    foreach (var method in service.MethodArray)
                    {
                        // Lambda 接口不支持客户端流 (Client Streaming)
                        if (method.ClientStreaming) continue;

                        GenerateLambdaInterface(writer, method);
                    }
                    writer.Indent--;

                    // 6. Pimpl 模式成员与构造析构
                    writer.WriteLine("public:");
                    writer.Indent++;
                    writer.WriteLine("class Private;");
                    writer.WriteLine("Private* const d = nullptr;");
                    writer.WriteLine();
                    writer.WriteLine($"{className}();");
                    writer.WriteLine($"virtual ~{className}();");
                    writer.Indent--;

                    writer.Indent--; // 结束类
                    writer.WriteLine("};");
                    writer.WriteLine();
                }

                return sw.ToString();
            }
        }

        private void GenerateLambdaInterface(IndentedTextWriter writer, GrpcServiceMethod method)
        {
            // 定义响应 Lambda 类型
            writer.WriteLine($"typedef TFunction<void(const FGrpcResult& GrpcResult, const {method.OutputType}& Response)> F{method.Name}ResponseLambda;");

            if (method.ServerStreaming)
            {
                // 服务端流需要额外的完成回调
                writer.WriteLine($"typedef TFunction<void()> F{method.Name}FinishLambda;");
                writer.WriteLine($"void Call{method.Name}(const {method.InputType}& Request, F{method.Name}ResponseLambda ResponseLambda, F{method.Name}FinishLambda FinishLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);");
            }
            else
            {
                // 普通 Unary 调用
                writer.WriteLine($"void Call{method.Name}(const {method.InputType}& Request, F{method.Name}ResponseLambda ResponseLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);");
            }
            writer.WriteLine();
        }
    }
}
