using System.IO;
using System.CodeDom.Compiler;

namespace protoc_gen_turbolink.Template
{
    public class ServicePrivateCPP
    {
        private readonly GrpcServiceFile s;
        private readonly GenerateParam g;

        public ServicePrivateCPP(GrpcServiceFile _s, GenerateParam _g)
        {
            s = _s;
            g = _g;
        }

        public string TransformText()
        {
            using (var sw = new StringWriter())
            using (var writer = new IndentedTextWriter(sw, "\t"))
            {
                // 1. 文件头
                writer.WriteLine("//Generated by TurboLink CodeGenerator, do not edit!");
                writer.WriteLine($"#include \"{s.CamelFileName}Service_Private.h\"");

                // 2. 遍历 Service 和 Method
                foreach (var service in s.ServiceArray)
                {
                    foreach (var method in service.MethodArray)
                    {
                        // LambdaWrapper 仅用于非客户端流 (Unary 或 Server Streaming)
                        if (method.ClientStreaming) continue;

                        string wrapperClassName = $"U{service.Name}{method.Name}LambdaWrapper";

                        // 3. 生成 OnResponse 回调
                        GenerateOnResponse(writer, wrapperClassName, service, method);

                        // 4. 生成 OnContextStateChanged 回调 (仅针对 Server Streaming)
                        if (method.ServerStreaming)
                        {
                            GenerateOnContextStateChanged(writer, wrapperClassName, service, method);
                        }
                    }
                }
                return sw.ToString();
            }
        }

        private void GenerateOnResponse(IndentedTextWriter writer, string className, GrpcService service, GrpcServiceMethod method)
        {
            writer.WriteLine();
            writer.WriteLine($"void {className}::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const {method.OutputType}& Response)");
            writer.WriteLine("{");
            writer.Indent++;
            
            writer.WriteLine("if (_Handle != this->Handle) return;");
            writer.WriteLine();
            writer.WriteLine("ResponseLambda(GrpcResult, Response);");

            // 如果是普通 Unary 调用，收到响应后立即解除绑定
            if (!method.ServerStreaming)
            {
                writer.WriteLine($"InnerClient->On{method.Name}Response.RemoveDynamic(this, &{className}::OnResponse);");
            }

            writer.Indent--;
            writer.WriteLine("}");
        }

        private void GenerateOnContextStateChanged(IndentedTextWriter writer, string className, GrpcService service, GrpcServiceMethod method)
        {
            writer.WriteLine();
            writer.WriteLine($"void {className}::OnContextStateChanged(FGrpcContextHandle _Handle, EGrpcContextState NewState)");
            writer.WriteLine("{");
            writer.Indent++;

            writer.WriteLine("if (_Handle != this->Handle) return;");
            writer.WriteLine("if (NewState == EGrpcContextState::Done)");
            writer.WriteLine("{");
            writer.Indent++;

            // 触发完成回调
            writer.WriteLine("FinishLambda();");
            writer.WriteLine();

            // 流结束，解除所有回调绑定
            writer.WriteLine($"InnerClient->On{method.Name}Response.RemoveDynamic(this, &{className}::OnResponse);");
            writer.WriteLine($"InnerClient->OnContextStateChange.RemoveDynamic(this, &{className}::OnContextStateChanged);");

            writer.Indent--;
            writer.WriteLine("}");

            writer.Indent--;
            writer.WriteLine("}");
        }
    }
}
