<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>protoc_gen_turbolink</RootNamespace>
    <AssemblyName>protoc-gen-turbolink</AssemblyName>
    <Deterministic>false</Deterministic>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.24.4" />
    <PackageReference Include="Grpc.Net.Client" Version="2.47.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.2" />
    <PackageReference Include="System.CodeDom" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Template\ClientCPP.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>ClientCPP.cs</LastGenOutput>
    </Content>
    <Content Include="Template\ClientH.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>ClientH.cs</LastGenOutput>
    </Content>
    <Content Include="Template\ContextCPP.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>ContextCPP.cs</LastGenOutput>
    </Content>
    <Content Include="Template\ContextH.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>ContextH.cs</LastGenOutput>
    </Content>
    <Content Include="Template\MarshalingCPP.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>MarshalingCPP.cs</LastGenOutput>
    </Content>
    <Content Include="Template\MarshalingH.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>MarshalingH.cs</LastGenOutput>
    </Content>
    <Content Include="Template\MessageCPP.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>MessageCPP.cs</LastGenOutput>
    </Content>
    <Content Include="Template\MessageH.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>MessageH.cs</LastGenOutput>
    </Content>
    <Content Include="Template\NodeCPP.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>NodeCPP.cs</LastGenOutput>
    </Content>
    <Content Include="Template\NodeH.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>NodeH.cs</LastGenOutput>
    </Content>
    <Content Include="Template\ServiceCPP.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>ServiceCPP.cs</LastGenOutput>
    </Content>
    <Content Include="Template\ServiceH.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>ServiceH.cs</LastGenOutput>
    </Content>
    <Content Include="Template\ServicePrivateCPP.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>ServicePrivateCPP.cs</LastGenOutput>
    </Content>
    <Content Include="Template\ServicePrivateH.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>ServicePrivateH.cs</LastGenOutput>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Template\ClientCPP.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ClientCPP.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\ClientH.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ClientH.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\ContextCPP.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ContextCPP.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\ContextH.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ContextH.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\MarshalingCPP.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MarshalingCPP.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\MarshalingH.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MarshalingH.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\MessageCPP.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MessageCPP.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\MessageH.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MessageH.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\NodeCPP.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NodeCPP.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\NodeH.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NodeH.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\ServiceCPP.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ServiceCPP.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\ServiceH.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ServiceH.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\ServicePrivateCPP.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ServicePrivateCPP.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\ServicePrivateH.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ServicePrivateH.tt</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
</Project>