<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>protoc_gen_turbolink</RootNamespace>
    <AssemblyName>protoc-gen-turbolink</AssemblyName>
    <Deterministic>false</Deterministic>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.24.4" />
    <PackageReference Include="Grpc.Net.Client" Version="2.47.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.2" />
    <PackageReference Include="System.CodeDom" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
</Project>